input createQuestionInput {
  title: String!
  description: String!
}

input updateQuestionInput {
  title: String
  description: String
}

type Mutation {
  createQuestion(input: createQuestionInput!): Question!
  updateQuestion(
    id: ID!
    input: updateQuestionInput!
  ): Question!
  removeQuestion(id: ID!): Question!
  markQuestionAsResolved(id: ID!): Question!
}
