type UserProfile {
  fullName: String
  bio: String
}

type User {
  id: ID!
  email: EmailAddress
  role: String!
  profile: UserProfile
  createdAt: DateTime!
  questions: [Question]!
  answers: [Answer]!
}
